### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by sovitybot** [sovity/sovity-daps#4]
Please update the repository to include a Dependabot configuration file.
This will ensure our dependencies remain updated and secure.
Follow the guidelines in [creating Dependabot configuration files](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) to set it up properly.

Here's an example of the code:

```yaml
# .github/dependabot.yaml
---
version: 2
updates:
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

```
